In [29]:
import numpy as np
from scipy import stats

x = [5, 7, 2, 1, 3, 4, 8, 8, 6, 6]
q75, q25 = np.percentile(x, [75 ,25])
iqr = q75 - q25

In [30]:
iqr

3.5

In [31]:
iqr = np.subtract(*np.percentile(x, [75, 25]))
iqr

3.5

In [32]:
np.subtract.reduce(np.percentile(x, [75, 25]))

3.5

In [33]:
x=[1, 10, 6, 9, 2, 5, 6, 6, 5, 10]
x = np.array(x)
x


array([ 1, 10,  6,  9,  2,  5,  6,  6,  5, 10])

In [34]:
x.std()

2.8982753492378879

In [35]:
avg = x.mean()

x2 = []

for xs in x:
    x2.append((xs-avg)**2)
    
x2 = np.array(x2)

print x2

[ 25.  16.   0.   9.  16.   1.   0.   0.   1.  16.]


In [36]:
np.sqrt(x2.mean())

2.8982753492378879

In [37]:
x = np.array([3, 5, 5, 6, 7.5, 6, 5, 1, 10, 4])
x

array([  3. ,   5. ,   5. ,   6. ,   7.5,   6. ,   5. ,   1. ,  10. ,   4. ])

In [38]:
iqr = np.subtract.reduce(np.percentile(x, [75, 25]))
med = np.median(x)
iqr, med

(1.75, 5.0)

In [39]:
high = med+1.5*iqr
low = med-1.5*iqr

def outlier(el, high, low):
    
    outliers = []
    
    for x in el:
        if x>high or x<low:
            outliers.append(x)
            
    return outliers

outlier(x, high, low)

[1.0, 10.0]

In [41]:
x = np.array([12, 10, 11, 12, 11, 14, 15, 18, 21, 11])

x.mean(), np.median(x), x.std(), stats.mode(x)



(13.5, 12.0, 3.3837848631377261, (array([11]), array([ 3.])))

In [42]:
print  stats.mode(x)

(array([11]), array([ 3.]))


In [1]:
q=(190**4 - 120/0.3)*1780
q

2319713088000.0